---
title: "Project Proposal"
author: "Bellier Marie, Finini Massimo, Likoska Meri, Renger Xavier, Rodrigues Telo Ramos Vania "
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
   html_document:
      self_contained: FALSE
      theme: cerulean
      highlight: tango
      keep_tex: yes
---
<style>
body {
text-align: justify}
</style>


## Goals and impacts

An anime is a hand-drawn or computer animation originated from Japan. 
Anime describes all animated work, regardless of the style or origin. 
The anime industry consists of over 430 production companies, including major studios like Studio Ghibli, Sunrise, and Toei Animation. 
As of 2016, Japanese anime accounted for 60% of the world’s animated television shows.
The goal of our project would be to recommend anime to someone who would like to watch it according to certain criteria that he will give us.
This could save time for the viewers while offering them an anime in line with their expectations. 


## Plan

Our inspiration for this project came from two sources. 
The first was a presentation by a group from previous years that made recommendations for films. 
The second is that two people in our group have already worked on an anime database in a Machine Learning course. 
We decided that it would be interesting to exploit this data in a deeper way by creating an interactive platform with a Shiny app.


The data set that we are going to use is sourced from Kaggle [Anime dataset](https://www.kaggle.com/hernan4444/anime-recommendation-database-2020?select=watching_status.csv). 
It contains information about 17'562 anime and the preference of 325'772 different users.

For the moment we think that we will need to keep the following variables: 

- `MAL_ID`: Id of the anime

- `Name`: Name of the anime

- `Genders`: Genre of the anime

- `Type`: Types of anime (TV, movie...)

- `Episodes`: Number of chapters

- `Producers`: Producer of the anime

- `Studios`: Studios

- `Source`: Sources of anime (Manga, Light novel, Book...)

- `Duration`: Duration of the anime per episode

- `Rating`: Age rate of the anime:
  - `PG-13`: for teens 13 or older 
  - `G`: All Ages 
  - `PG`: Children 
  - `Rx`: Hentai 
  - `R`: 17+ (violence & profanity) 
  - `R+`: Mild Nudity

The goal of our project is to make the user of our application fill in a certain number of boxes in order to offer him the best anime recommendation: 
We can ask him which producer, studio, source, genre and type of anime he prefers. 
We can also ask him to give us some indications about the time he has to watch it (recommendation based on the number of episodes and their duration). 
Finally, with their age, we can also better target our recommendation thanks to the `Rating` variable. 

For this project, we will probably use the following packages: `knitr`, `shiny`'s packages, `devtools`, `roxygen2` and/or `pkgdown`.


## Timeline and milestones

Here is a timeline of our project organisation. You can see below it the responsible for each task. 

```{r, echo = FALSE, results = FALSE, message = FALSE, fig.width = 8}
library(remotes)
remotes::install_github("giocomai/ganttrify", force = TRUE)
library(ganttrify)

project_G5 <- tibble::tribble(~wp, ~activity, ~start_date, ~end_date,
                              "Organisation", "Control the To-Do list", 
                              "2021-11-01", "2021-12-20", 
                                         "Project flow", "Project Proposal", 
                              "2021-11-01", "2021-11-07", 
                                         "Project flow", 
                              "R/RcPP Functions, Package Skeleton",
                              "2021-11-07", "2021-11-24",
                                         "Project flow", "Shiny app, blog, description of Package",
                              "2021-11-24", "2021-12-08",
                                         "Project flow", 
                              "Video and finalization of the project",
                              "2021-12-08", "2021-12-15",
                                         "Presentation", "Final presentation", 
                              "2021-12-15", "2021-12-20") 

ganttrify(project = project_G5,
          by_date = TRUE,
          exact_date = TRUE,
          size_wp = 3,
          alpha_wp = 0.5,
          size_activity = 2,
          project_start_date = "2021-11-01")

```


## Management plan

In order to move forward with our project, we will meet every Wednesday morning on Zoom. 
We will always try to talk about the project but, having the homework in parallel, we may not talk about it only. 
Anyway, at the end of the fourth assignment, we will dedicate this time only to the project.

Here are the parts of the project, the first member in the parenthesis is the responsible, and the other will help him if needed:
  
R-Package:

- R/RcPP Functions with documentations (Massimo, Meri)
- Package Skeleton (Meri, Marie)
- Shiny App (Meri, Massimo)
- Description file of package (Vania, Xavier)
- Be sure that package can be installed from GitHub (Vania, Xavier)
- A vignette illustrating the package/shinyApp with example (Xavier, Vania)
      
Other:
  
- Blog (Marie, Vania)
- Explaining Video (Xavier, Vania)
- Control the To-Do list (issues) on github (Vania, Xavier)

