
#'@title Simply compute the amount of items selected in the selectizeInput
#'
#'@author Marie Bellier, Massimo Finini, Meri Likoska, Vania Rodrigues Telo Ramos, Xavier Renger
#'
#'@param id inputId of the selectizeInput
#'
#'@return return the number of values selected
#'
#'@export

selectize_count <- function(id){
  selectedcount <- length(unique(id))
}

#'@title Simply get the vector of names selected in the selectizeInput
#'
#'@author Marie Bellier, Massimo Finini, Meri Likoska, Vania Rodrigues Telo Ramos, Xavier Renger
#'
#'@param id inputId of the selectizeInput
#'
#'@return return a vector of the item names selected
#'
#'@export

selectize_names <- function(id){
  selectednames = id
}


#'@title Create numeric inputs depending on the selection of the user in the selectizeInput. You first need to run both `selectize_count()` and `selectize_names()` to run this.
#'
#'@author Marie Bellier, Massimo Finini, Meri Likoska, Vania Rodrigues Telo Ramos, Xavier Renger
#'
#'@param selectednames names recovered through `selectize_names()`
#'@param selectedcounts count recovered through `selectize_count()`
#'@param min_user minimum value of the numericInputs
#'@param max_user maximum value of the numericInputs
#'@param placeholder placeholder value in the numericInput
#'@param wanted_step step of the value in the numericInput
#'
#'@return return a vector containing the numbers the user selected from 1:10
#'
#'@export


create_numeric_input <- function(selectednames,
                                 selectedcounts,
                                 min_user = 1,
                                 max_user = 10,
                                 placeholder = 5,
                                 wanted_step = 0.5,
                                 id = "weight"){
  count = 1
  box_list <- list()
  for (count in 1:selectedcounts) {
    box_list[[count]] <- numericInput(
      inputId = sprintf("%s_%s",
                        id,
                        count),
      label = sprintf("%s Score",selectednames[count]),
      min = min_user,
      max = max_user,
      value = placeholder,
      step = wanted_step
    )
    count = count + 1
  }
  tagList(box_list)
}

#'@title Recover the weights that the user has put in the boxes generated by `create_numeric_input()`
#'
#'@author Marie Bellier, Massimo Finini, Meri Likoska, Vania Rodrigues Telo Ramos, Xavier Renger
#'
#'@param selectedcounts amount of variable selected in the selectize input
#'@param input input id from shiny
#'
#'@return return a vector containing the numbers the user selected from 1:10
#'
#'@export



score_recovery <- function(selectedcounts, input, id = "weight"){
  FD=1
  weight_list <- vector()
  for(FD in 1:selectedcounts){
    weight_list[FD] <- input[[sprintf("%s_%s", id, FD)]]
    FD = FD+1
  }
  weight_list
}

